<?php

namespace App\Filament\Support;

/**
 * Pemetaan ikon bawaan Filament ke Lucide (R-2.17).
 *
 * Filament memakai Heroicons secara bawaan. Daftar ini menimpa setiap alias ikon yang
 * disediakannya agar seluruh panel memakai satu set ikon; alias yang tidak ada di sini
 * tetap memakai Heroicons, jadi daftar ini digenerate dari nilai bawaan Filament sendiri.
 */
final class SipmaIcons
{
    /**
     * @return array<string, string>
     */
    public static function map(): array
    {
        return [
            'actions::action-group' => 'lucide-ellipsis-vertical',
            'actions::create-action.grouped' => 'lucide-plus',
            'actions::delete-action' => 'lucide-trash-2',
            'actions::delete-action.grouped' => 'lucide-trash-2',
            'actions::delete-action.modal' => 'lucide-trash-2',
            'actions::detach-action' => 'lucide-x',
            'actions::detach-action.modal' => 'lucide-x',
            'actions::dissociate-action' => 'lucide-x',
            'actions::dissociate-action.modal' => 'lucide-x',
            'actions::edit-action' => 'lucide-square-pen',
            'actions::edit-action.grouped' => 'lucide-square-pen',
            'actions::export-action.grouped' => 'lucide-download',
            'actions::force-delete-action' => 'lucide-trash-2',
            'actions::force-delete-action.grouped' => 'lucide-trash-2',
            'actions::force-delete-action.modal' => 'lucide-trash-2',
            'actions::import-action.grouped' => 'lucide-upload',
            'actions::modal.confirmation' => 'lucide-triangle-alert',
            'actions::replicate-action' => 'lucide-copy',
            'actions::replicate-action.grouped' => 'lucide-copy',
            'actions::restore-action' => 'lucide-undo-2',
            'actions::restore-action.grouped' => 'lucide-undo-2',
            'actions::restore-action.modal' => 'lucide-undo-2',
            'actions::view-action' => 'lucide-eye',
            'actions::view-action.grouped' => 'lucide-eye',
            'forms::components.builder.actions.clone' => 'lucide-copy',
            'forms::components.builder.actions.collapse' => 'lucide-chevron-up',
            'forms::components.builder.actions.delete' => 'lucide-trash-2',
            'forms::components.builder.actions.expand' => 'lucide-chevron-down',
            'forms::components.builder.actions.move-down' => 'lucide-arrow-down',
            'forms::components.builder.actions.move-up' => 'lucide-arrow-up',
            'forms::components.builder.actions.reorder' => 'lucide-arrow-up-down',
            'forms::components.file-upload.editor.actions.move-down' => 'lucide-circle-arrow-down',
            'forms::components.file-upload.editor.actions.move-left' => 'lucide-circle-arrow-left',
            'forms::components.file-upload.editor.actions.move-right' => 'lucide-circle-arrow-right',
            'forms::components.file-upload.editor.actions.move-up' => 'lucide-circle-arrow-up',
            'forms::components.file-upload.editor.actions.rotate-left' => 'lucide-undo-2',
            'forms::components.file-upload.editor.actions.rotate-right' => 'lucide-redo-2',
            'forms::components.file-upload.editor.actions.zoom-100' => 'lucide-maximize-2',
            'forms::components.file-upload.editor.actions.zoom-in' => 'lucide-zoom-in',
            'forms::components.file-upload.editor.actions.zoom-out' => 'lucide-zoom-out',
            'forms::components.key-value.actions.delete' => 'lucide-trash-2',
            'forms::components.key-value.actions.reorder' => 'lucide-arrow-up-down',
            'forms::components.repeater.actions.clone' => 'lucide-copy',
            'forms::components.repeater.actions.collapse' => 'lucide-chevron-up',
            'forms::components.repeater.actions.delete' => 'lucide-trash-2',
            'forms::components.repeater.actions.expand' => 'lucide-chevron-down',
            'forms::components.repeater.actions.move-down' => 'lucide-arrow-down',
            'forms::components.repeater.actions.move-up' => 'lucide-arrow-up',
            'forms::components.repeater.actions.reorder' => 'lucide-arrow-up-down',
            'forms::components.select.actions.create-option' => 'lucide-plus',
            'forms::components.select.actions.edit-option' => 'lucide-square-pen',
            'forms::components.text-input.actions.hide-password' => 'lucide-eye-off',
            'forms::components.text-input.actions.show-password' => 'lucide-eye',
            'forms::components.toggle-buttons.boolean.false' => 'lucide-x',
            'forms::components.toggle-buttons.boolean.true' => 'lucide-check',
            'infolists::components.icon-entry.false' => 'lucide-circle-x',
            'infolists::components.icon-entry.true' => 'lucide-circle-check',
            'notifications::notification.danger' => 'lucide-circle-x',
            'notifications::notification.info' => 'lucide-info',
            'notifications::notification.success' => 'lucide-circle-check',
            'notifications::notification.warning' => 'lucide-circle-alert',
            'panels::pages.dashboard.actions.filter' => 'lucide-funnel',
            'panels::pages.password-reset.request-password-reset.actions.login' => 'lucide-arrow-left',
            'panels::pages.password-reset.request-password-reset.actions.login.rtl' => 'lucide-arrow-right',
            'panels::resources.pages.edit-record.navigation-item' => 'lucide-square-pen',
            'panels::resources.pages.manage-related-records.navigation-item' => 'lucide-layers',
            'panels::resources.pages.view-record.navigation-item' => 'lucide-eye',
            'panels::tenant-menu.billing-button' => 'lucide-credit-card',
            'panels::tenant-menu.profile-button' => 'lucide-settings',
            'panels::tenant-menu.registration-button' => 'lucide-plus',
            'panels::user-menu.logout-button' => 'lucide-log-out',
            'panels::user-menu.profile-item' => 'lucide-circle-user',
            'tables::actions.disable-reordering' => 'lucide-check',
            'tables::actions.enable-reordering' => 'lucide-arrow-up-down',
            'tables::actions.filter' => 'lucide-funnel',
            'tables::actions.group' => 'lucide-layers',
            'tables::actions.open-bulk-actions' => 'lucide-ellipsis-vertical',
            'tables::actions.toggle-columns' => 'lucide-columns-3',
            'tables::columns.icon-column.false' => 'lucide-circle-x',
            'tables::columns.icon-column.true' => 'lucide-circle-check',
            'tables::empty-state' => 'lucide-x',
            'tables::filters.query-builder.constraints.boolean' => 'lucide-circle-check',
            'tables::filters.query-builder.constraints.date' => 'lucide-calendar',
            'tables::filters.query-builder.constraints.number' => 'lucide-variable',
            'tables::filters.query-builder.constraints.relationship' => 'lucide-maximize-2',
            'tables::filters.query-builder.constraints.select' => 'lucide-chevrons-up-down',
            'tables::filters.query-builder.constraints.text' => 'lucide-languages',
            'filament-notifications::database.modal.empty.description' => 'lucide-bell-off',
            'filament-notifications::database.modal.empty.heading' => 'lucide-bell-off',
            'notifications::database.modal.empty-state' => 'lucide-bell-off',
            'panels::sidebar.collapse-button' => 'lucide-panel-left',
            'panels::sidebar.collapse-button.rtl' => 'lucide-panel-right',
            'panels::sidebar.expand-button' => 'lucide-panel-left',
            'panels::sidebar.expand-button.rtl' => 'lucide-panel-right',
            'forms:components.checkbox-list.search-field' => 'lucide-search',
            'modal.close-button' => 'lucide-x',
            'notifications::notification.close-button' => 'lucide-x',
            'panels::global-search.field' => 'lucide-search',
            'panels::sidebar.group.collapse-button' => 'lucide-chevron-up',
            'panels::topbar.close-sidebar-button' => 'lucide-x',
            'panels::topbar.group.toggle-button' => 'lucide-chevron-down',
            'panels::topbar.open-database-notifications-button' => 'lucide-bell',
            'panels::topbar.open-sidebar-button' => 'lucide-menu',
            'panels::widgets.account.logout-button' => 'lucide-log-out',
            'panels::widgets.filament-info.open-documentation-button' => 'lucide-book-open',
            'section.collapse-button' => 'lucide-chevron-down',
            'tables::columns.collapse-button' => 'lucide-chevron-down',
            'tables::filters.remove-all-button' => 'lucide-x',
            'tables::grouping.collapse-button' => 'lucide-chevron-up',
            'tables::search-field' => 'lucide-search',
        ];
    }
}
